"""multi image + blog html

Revision ID: e17690d95e99
Revises: 86c534eea648
Create Date: 2026-04-19 20:24:38.352112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e17690d95e99'
down_revision = '86c534eea648'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.drop_column('image')

    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=200), autoincrement=False, nullable=True))

    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=200), autoincrement=False, nullable=True))

    op.drop_table('vehicle_image')
    # ### end Alembic commands ###
